
pipeline {
    agent { any }
    stages {
        stage ('build') {
            
            steps {
                echo "hello build"
            }
        }
        stage( 'stage') {
            steps {
                script {
                    echo "hello stage"
                      

                   
                    }
                }
            }
        }
    }
    post {
        
        cleanup {
            deleteDir() /* clean up the workspace */    
        }
    }
}
